# 管理端口的开放配置
management:
  endpoints:
    web:
      exposure:
        include: env,encrypt
  endpoint:
    env:
      enabled: true

spring:
  profiles:
    active: dev
  datasource:
    druid:
      #########################  数据库配置  ################################
      ## JDBC连接 配置
      url: 'jdbc:mysql://127.0.0.1:3306/agent_tool'
      username: 'root'
      password: 'pwsd123456'
      # 8.0的Driver
      driver-class-name: 'com.mysql.cj.jdbc.Driver'
      ########### 连接池配置